"""
Automatically generated module. COPYRIGHT CENIT AG 2024.
"""


from .OlpCorePythonAttribute import *

class OlpCorePythonIntegerAttribute(OlpCorePythonAttribute):
      def GetValue(self) -> int:   ...
      def GetMinimum(self) -> int:   ...
      def GetMaximum(self) -> int:   ...
      def GetStepSize(self) -> int:   ...
