"""
Automatically generated module. COPYRIGHT CENIT AG 2024.
"""


from .OlpCorePythonAttribute import *

class OlpCorePythonDoubleAttribute(OlpCorePythonAttribute):
      def GetValue(self) -> float:   ...
      def GetMinimum(self) -> float:   ...
      def GetMaximum(self) -> float:   ...
      def GetStepSize(self) -> float:   ...
